# Generated by Django 5.2.7 on 2025-10-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stundents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srollno', models.CharField(max_length=10)),
                ('sname', models.CharField(max_length=64)),
                ('sphoneno', models.IntegerField()),
                ('sm1', models.IntegerField()),
                ('sm2', models.IntegerField()),
                ('sm3', models.IntegerField()),
            ],
        ),
    ]
